[Journal]
Storage=persistent
Compress=yes
Seal=yes
SplitMode=uid
SystemMaxUse=500M
SystemKeepFree=1G
SystemMaxFileSize=64M
SystemMaxFiles=8
RuntimeMaxUse=100M
MaxRetentionSec=14day
MaxFileSec=1day
ForwardToSyslog=no
ForwardToWall=no
RateLimitIntervalSec=30s
RateLimitBurst=10000
