upstream docker_daemon {
    server unix:/var/run/docker.sock;
}

server {
    listen 2375;

    location ~ "^/v[0-9.]+/(.*)$" {
        proxy_pass http://docker_daemon/$1$is_args$args;
        proxy_http_version 1.1;
        proxy_set_header Host docker;
        proxy_set_header Connection "";
        proxy_read_timeout 600;
        proxy_send_timeout 600;
        proxy_buffering off;
    }

    location / {
        proxy_pass http://docker_daemon;
        proxy_http_version 1.1;
        proxy_set_header Host docker;
        proxy_set_header Connection "";
        proxy_read_timeout 600;
        proxy_send_timeout 600;
        proxy_buffering off;
    }
}
