---
- name: restart monitoring
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_dir }}"
    state: restarted

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true
